### PR TITLE
Update metadata | Add .gitignore

### PR DESCRIPTION
**Pull request by vipulgupta2048**
**Updated following parameters**
`url`, `urls`
Will be adding screenshots
Added .gitignore file.

### CODE REVIEW

**Comment by rhl-bthr** [comment]
Reviewed to 3e83264

**Comment by quozl** [comment]
Reviewed to 3e83264.

On https://github.com/sugarlabs/jukebox-activity/pull/18/commits/b69e83a5a5cb67dff87b09a67ac8e6a5f5873eb1 it wasn't clear to me how you arrived at your _license_ metadata changes, the commit message said nothing about it, so I looked at the source.

* _license_ should begin with LGPLv2.1+ because that's the license of the primary source file `activity.py`, and most of the other Python files,
* _license_ should end with or have GPLv2+ because that's the license of the `setup.py` file,
* _license_ should not list LGPLv2+, because there's no file with that license.

For some reason, your merge commit fixed this.

Why _fun_ in _tags_?

Would have merged, but you said
> Will be adding screenshots

So considering this a work in progress pull request.

**Comment by vipulgupta2048** [comment]
So what happened was, I cloned this activity a while ago and hence my branch was trailing behind https://github.com/sugarlabs/jukebox-activity/commit/93519d1967db4773f6caa2fcb5e9ffd825e0368f which already fixed the license metadata, I made the change without knowing about it.
 
I observed the same when It created a conflict while making a PR. Hence the merge commit fixed it. 

I thought fun could be a cool tag, Should I remove it?
Regarding Screenshots, the Jukebox activity didn't start on my system #21 
I might be doing something wrong.

**Comment by quozl** [comment]
Okay, rather than add merge commits, rebase your patches against the master branch, that way we don't have to (a) review merge commits, (b) allow merge commits into the retained history (they make `git bisect` harder), (c) squash on your behalf, or (d) talk so much about it.  ;-)

Eventually we're going to have all the tags translated into all supported languages, so while it is cool to add fun tags, it is better to be exact with them.  _Fun_ is very subjective.  For some learners, their culture does not allow enjoyment of learning to be displayed too much, so they might avoid _fun_.

https://github.com/sugarlabs/jukebox-activity/issues/21 should be fixed for you now?

**Comment by vipulgupta2048** [comment]
> Eventually we're going to have all the tags translated into all supported languages, so while it is cool to add fun tags, it is better to be exact with them. Fun is very subjective. For some learners, their culture does not allow enjoyment of learning to be displayed too much, so they might avoid fun.

Damn, good to know about that. 

> #21 should be fixed for you now?

I tried deleting the Python-Pillow package and following the steps that you mentioned but it didn't work. I was thinking of getting the screenshots from someone else.

**Comment by quozl** [comment]
Thanks.  Reviewed to 96d67af.

* [ ] _music_ is inadequate as a tag, as the activity can also play audio books, videos, and presentations.

**Comment by vipulgupta2048** [comment]
How about media?

**Comment by quozl** [comment]
How about System?

**Comment by vipulgupta2048** [comment]
Works with me. Adding.

**Comment by quozl** [comment]
Push.

**Comment by quozl** [comment]
> > Works with me.  Adding.

> Push.

Gave up waiting, did it myself, thanks!

**Pull request merged**
